name: social_app
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  intl: ^0.18.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  conditional_builder_null_safety: ^0.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.1.0
  image_picker: ^1.0.0
  #firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.4
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.4.4
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/
  fonts:
    - family: Jannah
      fonts:
         - asset: assets/fonts/Jannah_font.ttf
           weight: 700
    - family: IconBroken
      fonts:
         - asset: assets/fonts/icons.ttf
